// Code generated by wit-bindgen-go. DO NOT EDIT.

package fetcher

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "sd2k:go-component-example/fetcher@0.1.0".
var Exports struct {
	// Fetch represents the caller-defined, exported function "fetch".
	//
	//	fetch: func(url: string) -> result<string, string>
	Fetch func(url string) (result cm.Result[string, string, string])
}
